import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
const mocks = vi.hoisted(() => ({ auth: { isAuthenticated: false, isSimpleMode: false, user: { id: 1, balance: 0 } }, app: { siteName: 'Example', cachedPublicSettings: { api_base_url: 'https://gateway.example.com', custom_endpoints: [], community_links: [] }, fetchPublicSettings: vi.fn() }, keys: vi.fn(), groups: vi.fn(), subscriptions: vi.fn(), stats: vi.fn(), monitors: vi.fn(), clipboard: vi.fn() }))
vi.mock('vue-i18n', async (importOriginal) => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key, locale: { value: 'zh' } }) }))
vi.mock('@/stores/auth', () => ({ useAuthStore: () => mocks.auth }))
vi.mock('@/stores/app', () => ({ useAppStore: () => mocks.app }))
vi.mock('@/composables/useClipboard', () => ({ useClipboard: () => ({ copied: { value: false }, copyToClipboard: mocks.clipboard }) }))
vi.mock('@/api/keys', () => ({ list: mocks.keys }))
vi.mock('@/api/groups', () => ({ getAvailable: mocks.groups }))
vi.mock('@/api/subscriptions', () => ({ getActiveSubscriptions: mocks.subscriptions }))
vi.mock('@/api/usage', () => ({ usageAPI: { getDashboardStats: mocks.stats } }))
vi.mock('@/utils/featureFlags', () => ({ FeatureFlags: { payment: 'payment', modelPlaza: 'model' }, isFeatureFlagEnabled: () => false }))
import ConnectView from '../ConnectView.vue'
import GettingStarted from '@/components/user/dashboard/GettingStarted.vue'
const global = { stubs: { AppLayout: { template: '<main><slot /></main>' }, PlazaNavBar: true, UseKeyContent: { props: ['apiKey', 'platform', 'baseUrl'], template: '<div data-testid="guide">{{ apiKey }}|{{ platform }}|{{ baseUrl }}</div>' }, CommunitySection: true, BillingExplanation: true, RouterLink: { props: ['to'], template: '<a :href="to"><slot /></a>' } } }
beforeEach(() => { vi.clearAllMocks(); mocks.auth.isAuthenticated = false; mocks.keys.mockResolvedValue({ items: [], total: 0 }); mocks.groups.mockResolvedValue([]); mocks.subscriptions.mockResolvedValue([]); mocks.stats.mockResolvedValue({ total_requests: 0 }) })
describe('connection and onboarding behavior', () => {
 it('offers the six-step guide with official ChatGPT and CC Switch downloads and existing key actions', async () => {
   const w = mount(ConnectView, { global })
   await flushPromises()
   const guide = w.get('#cc-switch-guide')
   expect(guide.findAll('ol > li')).toHaveLength(6)
   const appStep = guide.get('#cc-switch-app')
   expect(appStep.findAll('[role="group"] button').map(b => b.text())).toEqual(['macOS', 'Windows'])
   await appStep.findAll('[role="group"] button')[0].trigger('click')
   expect(appStep.get('a').attributes('href')).toBe('https://persistent.oaistatic.com/codex-app-prod/Codex.dmg')
   expect(appStep.text()).toContain('commercial.ccSwitch.app.mac')
   await appStep.findAll('[role="group"] button')[1].trigger('click')
   expect(appStep.get('a').attributes('href')).toBe('https://apps.microsoft.com/detail/9PLM9XGG6VKS')
   expect(appStep.get('a').attributes('target')).toBe('_blank')
   expect(appStep.get('a').attributes('rel')).toBe('noopener noreferrer')
   expect(guide.get('a[href="https://ccswitch.io/"]').attributes('rel')).toBe('noopener noreferrer')
   expect(guide.get('a[href="/keys"]').exists()).toBe(true)
   expect(guide.get('a[href="/usage"]').exists()).toBe(true)
   expect(guide.findAll('a').some(a => a.attributes('href')?.startsWith('ccswitch:'))).toBe(false)
   const downloadTabs = () => guide.get('#cc-switch-download').findAll('[role="group"] button')
   await downloadTabs()[1].trigger('click')
   expect(guide.text()).toContain('commercial.ccSwitch.download.windows')
   expect(downloadTabs()[1].attributes('aria-pressed')).toBe('true')
   expect(guide.text()).toContain('https://gateway.example.com')
   expect(mocks.keys).not.toHaveBeenCalled()
   w.unmount()
 })
 it('offers a copyable prompt that lets Codex enable its built-in image generation', async () => {
   const w = mount(ConnectView, { global })
   await flushPromises()
   const images = w.get('#cc-switch-guide').get('#cc-switch-images')
   expect(images.text()).toContain('commercial.ccSwitch.images.title')
   expect(images.get('[data-testid="image-prompt"]').text()).toBe('commercial.ccSwitch.images.prompt')
   expect(w.get('#cc-switch-guide').findAll('ol > li')).toHaveLength(6)
   await images.get('button').trigger('click')
   await flushPromises()
   expect(mocks.clipboard).toHaveBeenCalledWith('commercial.ccSwitch.images.prompt', 'commercial.ccSwitch.images.copied')
   w.unmount()
 })
 it('enlarges an instructional image and restores focus when closed with Escape', async () => {
   const w = mount(ConnectView, { global, attachTo: document.body })
   const opener = w.get('#cc-switch-create figure button')
   ;(opener.element as HTMLButtonElement).focus()
   await opener.trigger('click')
   await flushPromises()
   expect(document.querySelector('[role="dialog"] img')?.getAttribute('src')).toBe('/guides/cc-switch/create-key.webp')
   document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
   await flushPromises()
   await vi.waitFor(() => expect(document.querySelector('[role="dialog"]')).toBeNull())
   expect(document.activeElement).toBe(opener.element)
   w.unmount()
 })
 it('uses key usage for simple mode without adding a hidden usage route', async () => {
   mocks.auth.isSimpleMode = true
   const w = mount(ConnectView, { global })
   expect(w.get('#cc-switch-verify a').attributes('href')).toBe('/keys')
   w.unmount()
   mocks.auth.isSimpleMode = false
 })
 it('opens anonymous guidance on the focused OpenAI and Codex path without requesting private keys', async () => { const w = mount(ConnectView, { global }); await flushPromises(); expect(mocks.keys).not.toHaveBeenCalled(); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY|openai|'); expect(w.findAll('select')[0].element.value).toBe('openai'); expect(w.text()).toContain('commercial.connect.preview'); w.unmount() })
 it('returns to the connection center after login', () => { const w = mount(ConnectView, { global }); expect(w.findComponent({ name: 'PlazaNavBar' }).props('loginRedirect')).toBe('/connect'); w.unmount() })
 it('stops key pagination when a page is empty', async () => { mocks.auth.isAuthenticated = true; mocks.keys.mockResolvedValue({ items: [], total: 10 }); const w = mount(ConnectView, { global }); await flushPromises(); expect(mocks.keys).toHaveBeenCalledTimes(1); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); w.unmount() })
 it('shows only usable personal keys and keeps generic mode as the default', async () => { mocks.auth.isAuthenticated = true; mocks.keys.mockResolvedValue({ items: [{ id: 1, name: 'active', key: 'test-only-key', status: 'active', group: { platform: 'openai' } }, { id: 2, name: 'disabled', key: 'disabled-key', status: 'inactive', group: { platform: 'openai' } }, { id: 3, name: 'expired', status: 'active', expires_at: '2020-01-01', group: { platform: 'openai' } }], total: 3 }); const w = mount(ConnectView, { global }); await flushPromises(); const select = w.findAll('select')[0]; expect(select.text()).toContain('active'); expect(select.text()).not.toContain('disabled'); expect(select.text()).not.toContain('expired'); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); await select.setValue('1'); expect(w.get('[data-testid="guide"]').text()).toContain('test-only-key|openai|https://gateway.example.com'); w.unmount() })
 it('keeps generic instructions available after a private API failure', async () => { mocks.auth.isAuthenticated = true; mocks.keys.mockRejectedValue(new Error('offline')); const w = mount(ConnectView, { global }); await flushPromises(); expect(w.get('[role="alert"]').text()).toContain('commercial.connect.failed'); expect(w.text()).not.toContain('commercial.connect.noKeys'); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); w.unmount() })
 it('explains missing access without inventing completion or exposing a disabled purchase entry', async () => { const w = mount(GettingStarted, { global }); await flushPromises(); expect(w.text()).toContain('commercial.onboarding.noGroups'); expect(w.text()).toContain('commercial.onboarding.noFunding'); expect(w.find('a[href="/purchase"]').exists()).toBe(false); expect(w.findAll('li').every(li => li.text().includes('commercial.onboarding.next'))).toBe(true); await w.get('input[type="checkbox"]').setValue(true); expect(w.findAll('li')[2].text()).toContain('commercial.onboarding.done'); w.unmount() })
 it('does not interpret a failed account lookup as no access', async () => { mocks.groups.mockRejectedValue(new Error('offline')); const w = mount(GettingStarted, { global }); await flushPromises(); expect(w.get('[role="alert"]').text()).toContain('commercial.onboarding.failed'); expect(w.text()).not.toContain('commercial.onboarding.noGroups'); w.unmount() })
})
